function csvTable = importfileCobi_v1(filename, dataLines)
%IMPORTFILE Import data from a text file
%  MYEXCEL1557911972 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  MYEXCEL1557911972 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  myExcel1557911972 = importfile("L:\EBI\02_ENG\01_ENG1\10_UserOffice\Schnee\04_Algos\05_CrashAlgo\Simulink\CrashAlgoSchnee\myExcel1557911972.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 15-May-2019 11:23:52

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["AccX", "Y", "Z", "Gyrx", "y", "z", "pressure", "VarName8"];
%opts.VariableNames = ["Time","AccX", "Y", "Z", "Gyrx", "y", "z", "pressure"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "string"];
opts = setvaropts(opts, 8, "WhitespaceRule", "preserve");
opts = setvaropts(opts, 8, "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
csvTable = readtable(filename, opts);

end