function logfile = importfileCobi_v6(filename, dataLines)
%IMPORTFILE Import data from a text file
%  IMULOGFILE20190604T105120 = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  IMULOGFILE20190604T105120 = IMPORTFILE(FILE, DATALINES) reads data
%  for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  IMUlogFile20190604T105120 = importfile("L:\EBI\02_ENG\01_ENG1\10_UserOffice\Schnee\04_Algos\05_CrashAlgo\Simulink\CrashAlgoSchnee\CobiData\CobiAppIOS\IMU-logFile-2019-06-04T105120.653+0200_detachHub_v6.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 04-Jun-2019 10:54:37

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 15);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["Time", "counter", "accTime", "AccX", "Y", "Z", "gyroCounter", "gyroTime", "Gyrx", "y", "z", "isHubConnected", "pressure", "speed", "VarName15"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string"];
opts = setvaropts(opts, 15, "WhitespaceRule", "preserve");
opts = setvaropts(opts, 15, "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
logfile = readtable(filename, opts);

end