function logfile = importfileCobiAndroid_v4(filename, dataLines)
%IMPORTFILE Import data from a text file
%  SENSORLOGANDROIDV1 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  SENSORLOGANDROIDV1 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  sensorlogandroidv1 = importfile("L:\EBI\02_ENG\01_ENG1\10_UserOffice\Schnee\04_Algos\05_CrashAlgo\Simulink\CrashAlgoSchnee\CobiData\crashAndroidNils\2019_05_28_13_13_sensorlog_android_v1.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 28-May-2019 13:15:12

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 13);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["Time", "accCounter", "accTime", "accX", "accY", "accZ", "gyroCounter", "gyroTime", "gyroX", "gyroY", "gyroZ", "pressure", "speed"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
logfile = readtable(filename, opts);

end